import pickle
from src.gestor_aplicacion.campeonato.Campeonato import Campeonato
from src.gestor_aplicacion.campeonato.DirectorCarrera import DirectorCarrera
from src.gestor_aplicacion.campeonato.Equipo import Equipo
from src.gestor_aplicacion.campeonato.VehiculoCarrera import VehiculoCarrera
from src.gestor_aplicacion.paddock.Patrocinador import Patrocinador
from src.gestor_aplicacion.paddock.Pieza import Pieza
from src.gestor_aplicacion.paddock.Piloto import Piloto
from src.gestor_aplicacion.paddock.Chasis import Chasis
from src.gestor_aplicacion.paddock.Circuito import Circuito
from src.gestor_aplicacion.ubicaciones.Ciudad import Ciudad
from src.gestor_aplicacion.ubicaciones.Continente import Continente

class Serializado():

    @staticmethod
    def serializar():

        #CAMPEONATOS
        archivo = open('src/base_Datos/temp/datosCampeonatos.txt','wb')
        pickle.dump(Campeonato.getCampeonatos(), archivo)
        archivo.close()

        #CIUDADES
        archivo = open('src/base_Datos/temp/datosCiudades.txt','wb')
        pickle.dump(Ciudad.get_lista_ciudades(), archivo)
        archivo.close()

        #DIRECTORES
        archivo = open('src/base_Datos/temp/datosDirectores.txt','wb')
        pickle.dump(DirectorCarrera.getListaDirectores(), archivo)
        archivo.close()

        #EQUIPOS
        archivo = open('src/base_Datos/temp/datosEquipos.txt','wb')
        pickle.dump(Equipo.getEquipos(), archivo)
        archivo.close()

        #PATROCINADORES
        archivo = open('src/base_Datos/temp/datosPatrocinadores.txt','wb')
        pickle.dump(Patrocinador.getPatrocinadores(), archivo)
        archivo.close()

        #PIEZAS
        archivo = open('src/base_Datos/temp/datosPiezas.txt','wb')
        pickle.dump(Pieza.getPiezas(), archivo)
        archivo.close()

        #PILOTOS
        archivo = open('src/base_Datos/temp/datosPilotos.txt','wb')
        pickle.dump(Piloto.getPilotos(), archivo)
        archivo.close()

        #CHASIS
        archivo = open('src/base_Datos/temp/datosChasis.txt','wb')
        pickle.dump(Chasis.get_lista_chasis(), archivo)
        archivo.close()

        #VEHICULO CARRERA
        archivo = open('src/base_Datos/temp/datosVehiculos.txt','wb')
        pickle.dump(VehiculoCarrera.getVehiculos(), archivo)
        archivo.close()

        #CIRCUITOS
        archivo = open('src/base_Datos/temp/datosCircuitos.txt','wb')
        pickle.dump(Circuito.get_circuitos(), archivo)####
        archivo.close()

    @staticmethod
    def crearObjetos():

        # Patrocinadores
        Patrocinador("Rolex")
        Patrocinador("Heineken")
        Patrocinador("Emirates")
        Patrocinador("Pirelli")
        Patrocinador("DHL")
        Patrocinador("Petronas")
        Patrocinador("Santander")
        Patrocinador("Red Bull")
        Patrocinador("Shell")
        Patrocinador("Honda")
        Patrocinador("Aston Martin")
        Patrocinador("Lenovo")
        Patrocinador("Acer")
        Patrocinador("UPS")
        Patrocinador("Oracle")
        Patrocinador("Cisco")
        Patrocinador("TotalEnergies")
        Patrocinador("AWS (Amazon Web Services)")
        Patrocinador("Cognizant")
        Patrocinador("BWT (Best Water Technology)")
        Patrocinador("Rich Energy")
        Patrocinador("INEOS")
        Patrocinador("Infiniti")
        Patrocinador("ROKiT")
        Patrocinador("Mouser Electronics")
        Patrocinador("Epson")
        Patrocinador("Claro")
        Patrocinador("Martini")
        Patrocinador("Ray-Ban")
        Patrocinador("Hugo Boss")
        Patrocinador("Philips")
        Patrocinador("IWC Schaffhausen")
        Patrocinador("Weichai")
        Patrocinador("AirAsia")
        Patrocinador("Viessmann")
        Patrocinador("Giti Tire")
        Patrocinador("188BET")
        Patrocinador("Brembo")
        Patrocinador("UBS")
        Patrocinador("Aldo")
        Patrocinador("UST Global")
        Patrocinador("Tommy Hilfiger")
        Patrocinador("PerkinElmer")

        # CIUDADES

        # Ciudades en Africa
        ciudadDelSahara = Ciudad("Ciudad del Sahara", "Africa")
        casablanca = Ciudad("Casablanca", "Africa")
        elCairo = Ciudad("El Cairo", "Africa")
        johannesburgo = Ciudad("Johannesburgo", "Africa")
        marrakech = Ciudad("Marrakech", "Africa")
        ciudadDelCabo = Ciudad("Ciudad del Cabo", "Africa")
        tunez = Ciudad("Tunez", "Africa")
        argel = Ciudad("Argel", "Africa")
        dakar = Ciudad("Dakar", "Africa")
        nairobi = Ciudad("Nairobi", "Africa")
        lusaka = Ciudad("Lusaka", "Africa")
        khartoum = Ciudad("Khartoum", "Africa")
        kigali = Ciudad("Kigali", "Africa")
        luanda = Ciudad("Luanda", "Africa")
        windhoek = Ciudad("Windhoek", "Africa")
        gaborone = Ciudad("Gaborone", "Africa")
        antananarivo = Ciudad("Antananarivo", "Africa")
        abuja = Ciudad("Abuja", "Africa")
        kinshasa = Ciudad("Kinshasa", "Africa")
        bamako = Ciudad("Bamako", "Africa")

        # Ciudades en América
        ciudadDeMexico = Ciudad("Ciudad de Mexico", "America")
        saoPaulo = Ciudad("Sao Paulo", "America")
        buenosAires = Ciudad("Buenos Aires", "America")
        montreal = Ciudad("Montreal", "America")
        indianapolis = Ciudad("Indianapolis", "America")
        austin = Ciudad("Austin", "America")
        miami = Ciudad("Miami", "America")
        lasVegas = Ciudad("Las Vegas", "America")
        nuevaYork = Ciudad("Nueva York", "America")
        losAngeles = Ciudad("Los Angeles", "America")
        chicago = Ciudad("Chicago", "America")
        toronto = Ciudad("Toronto", "America")
        bogota = Ciudad("Bogota", "America")
        lima = Ciudad("Lima", "America")
        caracas = Ciudad("Caracas", "America")
        santiago = Ciudad("Santiago", "America")
        quito = Ciudad("Quito", "America")
        sanJuan = Ciudad("San Juan", "America")
        laHabana = Ciudad("La Habana", "America")
        rioDeJaneiro = Ciudad("Rio de Janeiro", "America")

        # Ciudades en Asia
        shanghai = Ciudad("Shanghai", "Asia")
        singapur = Ciudad("Singapur", "Asia")
        tokio = Ciudad("Tokio", "Asia")
        shenzhen = Ciudad("Shenzhen", "Asia")
        abuDabi = Ciudad("Abu Dabi", "Asia")
        bahrain = Ciudad("Bahrain", "Asia")
        kualaLumpur = Ciudad("Kuala Lumpur", "Asia")
        mumbai = Ciudad("Mumbai", "Asia")
        delhi = Ciudad("Delhi", "Asia")
        doha = Ciudad("Doha", "Asia")
        estambul = Ciudad("Estambul", "Asia")
        baku = Ciudad("Baku", "Asia")
        jeddah = Ciudad("Jeddah", "Asia")
        hanoi = Ciudad("Hanoi", "Asia")
        manila = Ciudad("Manila", "Asia")
        seoul = Ciudad("Seoul", "Asia")
        sriJayawardenepuraKotte = Ciudad("Sri Jayawardenepura Kotte", "Asia")
        kuwait = Ciudad("Kuwait", "Asia")
        yeda = Ciudad("Yeda", "Asia")
        dubai = Ciudad("Dubai", "Asia")
        
        # Ciudades en Europa
        monaco = Ciudad("Monaco", "Europa")
        barcelona = Ciudad("Barcelona", "Europa")
        milan = Ciudad("Milan", "Europa")
        hockenheim = Ciudad("Hockenheim", "Europa")
        budapest = Ciudad("Budapest", "Europa")
        spaFrancorchamps = Ciudad("Spa-Francorchamps", "Europa")
        monza = Ciudad("Monza", "Europa")
        suzuka = Ciudad("Suzuka", "Europa")
        nurburgring = Ciudad("Nurburgring", "Europa")
        montecarlo = Ciudad("Montecarlo", "Europa")
        londres = Ciudad("Londres", "Europa")
        paris = Ciudad("Paris", "Europa")
        berlin = Ciudad("Berlin", "Europa")
        amsterdam = Ciudad("Amsterdam", "Europa")
        viena = Ciudad("Viena", "Europa")
        varsovia = Ciudad("Varsovia", "Europa")
        roma = Ciudad("Roma", "Europa")
        lisboa = Ciudad("Lisboa", "Europa")
        estocolmo = Ciudad("Estocolmo", "Europa")
        oslo = Ciudad("Oslo", "Europa")

       # Ciudades en Oceanía
        melbourne = Ciudad("Melbourne", "Oceania")
        sydney = Ciudad("Sydney", "Oceania")
        adelaida = Ciudad("Adelaida", "Oceania")
        auckland = Ciudad("Auckland", "Oceania")
        perth = Ciudad("Perth", "Oceania")
        brisbane = Ciudad("Brisbane", "Oceania")
        wellington = Ciudad("Wellington", "Oceania")
        suva = Ciudad("Suva", "Oceania")
        honolulu = Ciudad("Honolulu", "Oceania")
        papeete = Ciudad("Papeete", "Oceania")
        nadi = Ciudad("Nadi", "Oceania")
        palmira = Ciudad("Palmira", "Oceania")
        darwin = Ciudad("Darwin", "Oceania")
        fiyi = Ciudad("Fiyi", "Oceania")
        boraBora = Ciudad("Bora Bora", "Oceania")
        noumea = Ciudad("Noumea", "Oceania")
        honolulu2 = Ciudad("Honolulu", "Oceania")
        goldCoast = Ciudad("Gold Coast", "Oceania")
        sydney2 = Ciudad("Sydney", "Oceania")
        perth2 = Ciudad("Perth", "Oceania") 

        Equipo.create_equipo("Mercedes-AMG Petronas Formula One Team")
        Equipo.create_equipo("Red Bull Racing")
        Equipo.create_equipo("Scuderia Ferrari")
        Equipo.create_equipo("McLaren F1 Team")
        Equipo.create_equipo("Aston Martin Cognizant Formula One Team")
        Equipo.create_equipo("Alpine F1 Team")
        Equipo.create_equipo("Scuderia AlphaTauri")
        Equipo.create_equipo("Alfa Romeo Racing")
        Equipo.create_equipo("Williams Racing")
        Equipo.create_equipo("Haas F1 Team")
        Equipo.create_equipo("Racing Point F1 Team")
        Equipo.create_equipo("Lotus F1 Team")
        Equipo.create_equipo("Renault F1 Team")
        Equipo.create_equipo("BMW Sauber F1 Team")
        Equipo.create_equipo("Brawn GP Formula One Team")
        Equipo.create_equipo("Caterham F1 Team")
        Equipo.create_equipo("Marussia F1 Team")
        Equipo.create_equipo("Virgin Racing")
        Equipo.create_equipo("HRT Formula 1 Team")
        Equipo.create_equipo("Minardi F1 Team")
        Equipo.create_equipo("Arrows Grand Prix International")
        Equipo.create_equipo("Sauber")
        Equipo.create_equipo("Ligier")
        Equipo.create_equipo("Jordan Grand Prix")
        Equipo.create_equipo("Prost Grand Prix")

        # Sedes de los equipos
        Equipo.sedes_equipos()

        #Campeonatos
        Campeonato.create_campeonato_base("Desafio del Lejano Oriente", 3, "Asia")
        Campeonato.create_campeonato_base("Ruta Europea de la Velocidad", 12, "Europa")
        Campeonato.create_campeonato_base("Aventura en Tierras Australes", 9, "Oceania")
        Campeonato.create_campeonato_base("Carrera de las Dunas", 6, "Africa")
        Campeonato.create_campeonato_base("Gran Carrera Panamericana", 11, "America")
        Campeonato.create_campeonato_base("Tour Asiatico de la Formula 1", 8, "Asia")
        Campeonato.create_campeonato_base("Rally Europeo de Velocidad", 10, "Europa")
        Campeonato.create_campeonato_base("Gran Desafio del Pacifico", 7, "Oceania")
        Campeonato.create_campeonato_base("Campeonato de las Arenas Rojas", 8, "Africa")
        Campeonato.create_campeonato_base("Carrera por America del Norte", 10, "America")
        Campeonato.create_campeonato_base("Recorrido por Asia Oriental", 7, "Asia")
        Campeonato.create_campeonato_base("Gran Tour Europeo", 12, "Europa")
        Campeonato.create_campeonato_base("Expedicion Oceanica", 9, "Oceania")
        Campeonato.create_campeonato_base("Carrera en el Sahara", 6, "Africa")
        Campeonato.create_campeonato_base("Carrera de las Americas", 11, "America")
        Campeonato.create_campeonato_base("Aventura en Asia Central", 8, "Asia")
        Campeonato.create_campeonato_base("Campeonato Europeo de la Velocidad", 10, "Europa")
        Campeonato.create_campeonato_base("Carrera austral", 7, "Oceania")
        Campeonato.create_campeonato_base("Rally del Desierto", 8, "Africa")
        Campeonato.create_campeonato_base("Gran Desafio Americano", 10, "America")
        Campeonato.create_campeonato_base("Carrera en la Muralla China", 8, "Asia")
        Campeonato.create_campeonato_base("Ruta Europea de la Formula 1", 12, "Europa")
        Campeonato.create_campeonato_base("Gran Gira Oceanica", 9, "Oceania")
        Campeonato.create_campeonato_base("Carrera de las Arenas Blancas", 8, "Africa")
        Campeonato.create_campeonato_base("Campeonato de las Americas", 10, "America")
        Campeonato.create_campeonato_base("Gran Carrera Asiatica", 7, "Asia")
        Campeonato.create_campeonato_base("Circuito Europeo de Velocidad", 10, "Europa")
        Campeonato.create_campeonato_base("Carrera en la Tierra de los Canguros", 9, "Oceania")
        Campeonato.create_campeonato_base("Carrera Saharaui", 6, "Africa")
        Campeonato.create_campeonato_base("Gran Ruta Panamericana", 11, "America")
        Campeonato.create_campeonato_base("Desafio de Asia Central", 8, "Asia")
        Campeonato.create_campeonato_base("Rally Europeo Continental", 10, "Europa")
        Campeonato.create_campeonato_base("Gran Desafio del Sur del Pacifico", 7, "Oceania")
        Campeonato.create_campeonato_base("Carrera de las Dunas Doradas", 8, "Africa")
        Campeonato.create_campeonato_base("Campeonato de las Americas del Sur", 10, "America")
        Campeonato.create_campeonato_base("Carrera en la Ruta de la Seda", 7, "Asia")
        Campeonato.create_campeonato_base("Tour Europeo de la Velocidad", 12, "Europa")
        Campeonato.create_campeonato_base("Carrera en la Tierra de los Kiwis", 9, "Oceania")
        Campeonato.create_campeonato_base("Gran Rally del Sahara", 6, "Africa")
        Campeonato.create_campeonato_base("Ruta Panamericana Extrema", 11, "America")
        Campeonato.create_campeonato_base("Carrera en el Lejano Oriente", 8, "Asia")
        Campeonato.create_campeonato_base("Campeonato Europeo de la Velocidad Extrema", 10, "Europa")
        Campeonato.create_campeonato_base("Carrera en la Costa Australiana", 9, "Oceania")
        Campeonato.create_campeonato_base("Carrera en el Desierto de los Faraones", 6, "Africa")
        Campeonato.create_campeonato_base("Gran Carrera de las Americas", 11, "America")
        Campeonato.create_campeonato_base("Carrera en el Lejano Oriente", 8, "Asia")
        Campeonato.create_campeonato_base("Campeonato Europa a toda Velocidad", 10, "Europa")
        Campeonato.create_campeonato_base("Carrera en la Costa Australiana", 9, "Oceania")
        Campeonato.create_campeonato_base("Campeonato de las Arenas", 8, "Africa")

        #Pilotos
        Piloto.create_random_piloto("Jack Brabham")
        Piloto.create_random_piloto("Graham Hill")
        Piloto.create_random_piloto("Alberto Ascari")
        Piloto.create_random_piloto("Sir Frank Williams")
        Piloto.create_random_piloto("Sir Jackie Stewart")
        Piloto.create_random_piloto("A.J. Foyt")
        Piloto.create_random_piloto("Ronnie Peterson")
        Piloto.create_random_piloto("Nico Rosberg")
        Piloto.create_random_piloto("Alan Jones")
        Piloto.create_random_piloto("Carlos Sainz")
        Piloto.create_random_piloto("Max Verstappen")
        Piloto.create_random_piloto("Jules Bianchi")
        Piloto.create_random_piloto("Jean Alesi")
        Piloto.create_random_piloto("Gerhard Berger")
        Piloto.create_random_piloto("Eddie Irvine")
        Piloto.create_random_piloto("Mark Webber")
        Piloto.create_random_piloto("Robert Kubica")
        Piloto.create_random_piloto("Juan Pablo Montoya")
        Piloto.create_random_piloto("David Coulthard")
        Piloto.create_random_piloto("Carlos Reutemann")
        Piloto.create_random_piloto("Clay Regazzoni")
        Piloto.create_random_piloto("Felipe Massa")
        Piloto.create_random_piloto("Valtteri Bottas")
        Piloto.create_random_piloto("Heikki Kovalainen")
        Piloto.create_random_piloto("Denny Hulme")
        Piloto.create_random_piloto("Jody Scheckter")
        Piloto.create_random_piloto("Jacques Laffite")
        Piloto.create_random_piloto("Olivier Panis")
        Piloto.create_random_piloto("Pastor Maldonado")
        Piloto.create_random_piloto("James Hunt")
        Piloto.create_random_piloto("Jochen Rindt")
        Piloto.create_random_piloto("Chris Amon")
        Piloto.create_random_piloto("John Surtees")
        Piloto.create_random_piloto("Patrick Depailler")
        Piloto.create_random_piloto("Peter Revson")
        Piloto.create_random_piloto("Ludovico Scarfiotti")
        Piloto.create_random_piloto("Tony Brooks")
        Piloto.create_random_piloto("Luigi Musso")
        Piloto.create_random_piloto("John Watson")
        Piloto.create_random_piloto("Michele Alboreto")
        Piloto.create_random_piloto("Vittorio Brambilla")
        Piloto.create_random_piloto("Jo Siffert")
        Piloto.create_random_piloto("Francois Cevert")
        Piloto.create_random_piloto("Dan Gurney")
        Piloto.create_random_piloto("Jo Bonnier")
        Piloto.create_random_piloto("Giancarlo Baghetti")
        Piloto.create_random_piloto("Troy Ruttman")
        Piloto.create_random_piloto("Alex Caffi")
        Piloto.create_random_piloto("Roberto Guerrero")
        Piloto.create_random_piloto("Brian Redman")
        Piloto.create_random_piloto("Giancarlo Fisichella")
        Piloto.create_random_piloto("Gerhard Mitter")
        Piloto.create_random_piloto("Jo Ramirez")
        Piloto.create_random_piloto("Jo Vonlanthen")
        Piloto.create_random_piloto("Marco Apicella")
        Piloto.create_random_piloto("Brian Naylor")
        Piloto.create_random_piloto("Ignazio Giunti")
        Piloto.create_random_piloto("Mike Beuttler")
        Piloto.create_random_piloto("Pierluigi Martini")
        Piloto.create_random_piloto("Michael Andretti")
        Piloto.create_random_piloto("Stefan Bellof")
        Piloto.create_random_piloto("Piero Taruffi")
        Piloto.create_random_piloto("David Kennedy")
        Piloto.create_random_piloto("Nino Farina")
        Piloto.create_random_piloto("Alberto Uria")
        Piloto.create_random_piloto("Luigi Villoresi")
        Piloto.create_random_piloto("Wolfgang von Trips")
        Piloto.create_random_piloto("Richie Ginther")
        Piloto.create_random_piloto("Wolfgang Seidel")
        Piloto.create_random_piloto("Sergio Mantovani")
        Piloto.create_random_piloto("Peter Gethin")
        Piloto.create_random_piloto("Luigi Fagioli")
        Piloto.create_random_piloto("Jose Froilan Gonzalez")
        Piloto.create_random_piloto("Harry Schell")
        Piloto.create_random_piloto("Robert Manzon")
        Piloto.create_random_piloto("Hans Herrmann")
        Piloto.create_random_piloto("Piero Carini")
        Piloto.create_random_piloto("Jacky Ickx")
        Piloto.create_random_piloto("Elio de Angelis")
        Piloto.create_random_piloto("Franco Rol")
        Piloto.create_random_piloto("Clemar Bucci")
        Piloto.create_random_piloto("Lucien Bianchi")
        Piloto.create_random_piloto("Eugenio Castellotti")
        Piloto.create_random_piloto("Cesar Baldaccini")
        Piloto.create_random_piloto("Andre Pilette")
        Piloto.create_random_piloto("Peter Whitehead")
        Piloto.create_random_piloto("Antonio Branca")
        Piloto.create_random_piloto("Philippe Etancelin")
        Piloto.create_random_piloto("Cesare Perdisa")
        Piloto.create_random_piloto("Jean Behra")
        Piloto.create_random_piloto("Mike Hawthorn")
        Piloto.create_random_piloto("Ettore Chimeri")
        Piloto.create_random_piloto("Johnny Claes")
        Piloto.create_random_piloto("Paul Frere")
        Piloto.create_random_piloto("Andre Simon")
        Piloto.create_random_piloto("Ken Wharton")
        Piloto.create_random_piloto("George Amick")
        Piloto.create_random_piloto("Paul Russo")
        Piloto.create_random_piloto("Masten Gregory")
        Piloto.create_random_piloto("Giorgio Scarlatti")
        Piloto.create_random_piloto("Paco Godia")
        Piloto.create_random_piloto("Elie Bayol")
        Piloto.create_random_piloto("Umberto Maglioli")
        Piloto.create_random_piloto("Ron Flockhart")
        Piloto.create_random_piloto("Luigi Piotti")
        Piloto.create_random_piloto("Bob Sweikert")
        Piloto.create_random_piloto("Johnny Boyd")
        Piloto.create_random_piloto("Larry Crockett")
        Piloto.create_random_piloto("Jerry Hoyt")
        Piloto.create_random_piloto("Henry Banks")
        Piloto.create_random_piloto("Jimmy Daywalt")
        Piloto.create_random_piloto("Ray Crawford")
        Piloto.create_random_piloto("Jimmy Bryan")
        Piloto.create_random_piloto("Pat Flaherty")
        Piloto.create_random_piloto("Larry Jackson")
        Piloto.create_random_piloto("Dick Rathmann")
        Piloto.create_random_piloto("Ed Elisian")
        Piloto.create_random_piloto("Johnnie Parsons")
        Piloto.create_random_piloto("Jud Larson")
        Piloto.create_random_piloto("Billy Garrett")
        Piloto.create_random_piloto("Ed Fitz-Gerald")
        Piloto.create_random_piloto("Jimmy Reece")
        Piloto.create_random_piloto("Eddie Russo")
        Piloto.create_random_piloto("Rodger Ward")
        Piloto.create_random_piloto("Johnny Thomson")
        Piloto.create_random_piloto("Mike Nazaruk")
        Piloto.create_random_piloto("Sam Hanks")
        Piloto.create_random_piloto("Eddie Johnson")
        Piloto.create_random_piloto("Bill Schindler")
        Piloto.create_random_piloto("Chuck Stevenson")
        Piloto.create_random_piloto("Duane Carter")
        Piloto.create_random_piloto("Bill Vukovich")
        Piloto.create_random_piloto("Johnny McDowell")
        Piloto.create_random_piloto("Tony Bettenhausen")
        Piloto.create_random_piloto("Pat O'Connor")
        Piloto.create_random_piloto("Jim Rathmann")
        Piloto.create_random_piloto("Tony Bonadies")
        Piloto.create_random_piloto("Dave Macdonald")
        Piloto.create_random_piloto("Gary Congdon")
        Piloto.create_random_piloto("Joe Sostilio")
        Piloto.create_random_piloto("Jack Turner")
        Piloto.create_random_piloto("Johnny White")
        Piloto.create_random_piloto("Bud Tingelstad")
        Piloto.create_random_piloto("Cliff Griffith")
        Piloto.create_random_piloto("Chuck Arnold")
        Piloto.create_random_piloto("Gene Hartley")
        Piloto.create_random_piloto("Mike Magill")
        Piloto.create_random_piloto("Al Herman")
        Piloto.create_random_piloto("Bobby Marshman")
        Piloto.create_random_piloto("Jim McWithey")
        Piloto.create_random_piloto("Bob Mathouser")
        Piloto.create_random_piloto("Dempsey Wilson")
        Piloto.create_random_piloto("Al Miller")
        Piloto.create_random_piloto("Eddie Sachs")
        Piloto.create_random_piloto("Charles Leclerc")
        Piloto.create_random_piloto("Chuck Rodee")
        Piloto.create_random_piloto("Don Freeland")
        Piloto.create_random_piloto("Buddy Lazier")
        Piloto.create_random_piloto("Joe Leonard")
        Piloto.create_random_piloto("Greg Weld")
        Piloto.create_random_piloto("Art Pollard")
        Piloto.create_random_piloto("Don Branson")
        Piloto.create_random_piloto("Rubens Barrichello")
        Piloto.create_random_piloto("Ricardo Zonta")
        Piloto.create_random_piloto("Nico Hulkenberg")
        Piloto.create_random_piloto("Alexander Albon")
        Piloto.create_random_piloto("Antonio Giovinazzi")
        Piloto.create_random_piloto("Takuma Sato")
        Piloto.create_random_piloto("Alexander Rossi")
        Piloto.create_random_piloto("Roland Ratzenberger")
        Piloto.create_random_piloto("Tomas Scheckter")
        Piloto.create_random_piloto("Max Chilton")
        Piloto.create_random_piloto("Reno Arnoux")
        Piloto.create_random_piloto("Henri Pescarolo")
        Piloto.create_random_piloto("Johnny Servoz-Gavin")
        Piloto.create_random_piloto("Maurice Trintignant")
        Piloto.create_random_piloto("Peter Collins")
        Piloto.create_random_piloto("Carlos Pace")
        Piloto.create_random_piloto("Hector Rebaque")
        Piloto.create_random_piloto("Ricardo Rodriguez")
        Piloto.create_random_piloto("Oscar Gonzalez")
        Piloto.create_random_piloto("Mario Andretti")

        # Directores de carrera
        DirectorCarrera.create_director_carrera("Charlie Whiting")
        DirectorCarrera.create_director_carrera("Michael Masi")
        DirectorCarrera.create_director_carrera("Herbie Blash")
        DirectorCarrera.create_director_carrera("Jacky Ickx")
        DirectorCarrera.create_director_carrera("Derek Ongaro")
        DirectorCarrera.create_director_carrera("Philippe Gachet")
        DirectorCarrera.create_director_carrera("Roland Bruynseraede")
        DirectorCarrera.create_director_carrera("Alain De Cadenet")
        DirectorCarrera.create_director_carrera("Roger Lane-Nott")
        DirectorCarrera.create_director_carrera("Bobby Rahal")
        DirectorCarrera.create_director_carrera("Jo Bauer")
        DirectorCarrera.create_director_carrera("Eduardo Freitas")
        DirectorCarrera.create_director_carrera("Paul Gutjahr")
        DirectorCarrera.create_director_carrera("Yves Bacquelaine")
        DirectorCarrera.create_director_carrera("Nick Craw")
        DirectorCarrera.create_director_carrera("Bjorn Nilsson")
        DirectorCarrera.create_director_carrera("Roger Peart")
        DirectorCarrera.create_director_carrera("Jean-Claude Lefebvre")
        DirectorCarrera.create_director_carrera("Tony Scott-Andrews")
        DirectorCarrera.create_director_carrera("Emanuele Pirro")
        DirectorCarrera.create_director_carrera("Gerd Ennser")
        DirectorCarrera.create_director_carrera("Joann Villeneuve")
        DirectorCarrera.create_director_carrera("Trevor Foster")
        DirectorCarrera.create_director_carrera("Erich Beck")
        DirectorCarrera.create_director_carrera("Richard Divila")
        DirectorCarrera.create_director_carrera("Dennis Carter")
        DirectorCarrera.create_director_carrera("Alan Donnelly")
        DirectorCarrera.create_director_carrera("Philip Gauthier")
        DirectorCarrera.create_director_carrera("Bruno Michel")
        DirectorCarrera.create_director_carrera("Garry Connelly")
        DirectorCarrera.create_director_carrera("Ian Reed")
        DirectorCarrera.create_director_carrera("Jose Abed")
        DirectorCarrera.create_director_carrera("Manfred Scheuer")
        DirectorCarrera.create_director_carrera("Steve Stringwell")
        DirectorCarrera.create_director_carrera("Yasumasa Arai")
        DirectorCarrera.create_director_carrera("Jorge H. Barados")
        DirectorCarrera.create_director_carrera("Walter Aeschlimann")
        DirectorCarrera.create_director_carrera("Eugenio Farcas")
        DirectorCarrera.create_director_carrera("Enzo Spano")
        DirectorCarrera.create_director_carrera("Joaquin Verdegay")
        DirectorCarrera.create_director_carrera("Niels Wittich")
        DirectorCarrera.create_director_carrera("Michel Boeri")
        DirectorCarrera.create_director_carrera("Hassan Al-Thawadi")
        DirectorCarrera.create_director_carrera("Jean-Pierre Nicolas")
        DirectorCarrera.create_director_carrera("Jean-Claude Basso")
        DirectorCarrera.create_director_carrera("Oscar Stafanini")
        
        #Circuitos
        
        Circuito.create_circuito("Circuito del Dragon")
        Circuito.create_circuito("Circuito Estelar")
        Circuito.create_circuito("Circuito del Horizonte")
        Circuito.create_circuito("Circuito de la Velocidad Suprema")
        Circuito.create_circuito("Circuito de las Sombras")
        Circuito.create_circuito("Circuito del Cielo Azul")
        Circuito.create_circuito("Circuito de la Luna Roja")
        Circuito.create_circuito("Circuito del Sol Eterno")
        Circuito.create_circuito("Circuito de las Estrellas Doradas")
        Circuito.create_circuito("Circuito de la Victoria Infinita")
        Circuito.create_circuito("Circuito del Viento Rapido")
        Circuito.create_circuito("Circuito del Rayo Veloz")
        Circuito.create_circuito("Circuito de la Maravilla Mecanica")
        Circuito.create_circuito("Circuito del Rugido del Motor")
        Circuito.create_circuito("Circuito de la Curva del Dragon")
        Circuito.create_circuito("Circuito de la Recta Sin Fin")
        Circuito.create_circuito("Circuito de la Sombra Luminosa")
        Circuito.create_circuito("Circuito del Desafio Supremo")
        Circuito.create_circuito("Circuito de la Pasion Veloz")
        Circuito.create_circuito("Circuito de la Aventura Extrema")
        Circuito.create_circuito("Circuito de la Noche Estrellada")
        Circuito.create_circuito("Circuito del Laberinto")
        Circuito.create_circuito("Circuito de las Dunas Ardientes")
        Circuito.create_circuito("Circuito del Oasis Veloz")
        Circuito.create_circuito("Circuito del Vortice")
        Circuito.create_circuito("Circuito de la Selva Secreta")
        Circuito.create_circuito("Circuito de la Magia Mecanica")
        Circuito.create_circuito("Circuito de la Euforia Veloz")
        Circuito.create_circuito("Circuito de la Lluvia de Estrellas")
        Circuito.create_circuito("Circuito de la Perfeccion Veloz")
        
        #Chasis
        Chasis.create_chasis("Mercedes", "W12")
        Chasis.create_chasis("Red Bull Racing", "RB16B")
        Chasis.create_chasis("Ferrari", "SF21")
        Chasis.create_chasis("McLaren", "MCL35M")
        Chasis.create_chasis("Aston Martin", "AMR21")
        Chasis.create_chasis("Alpine", "A521")
        Chasis.create_chasis("AlphaTauri", "AT02")
        Chasis.create_chasis("Williams", "FW43B")
        Chasis.create_chasis("Alfa Romeo", "C41")
        Chasis.create_chasis("Haas", "VF-21")
        Chasis.create_chasis("Mercedes", "W12")
        Chasis.create_chasis("Red Bull Racing", "RB16B")
        Chasis.create_chasis("Ferrari", "SF21")
        Chasis.create_chasis("McLaren", "MCL35M")
        Chasis.create_chasis("Aston Martin", "AMR21")
        Chasis.create_chasis("Alpine", "A521")
        Chasis.create_chasis("AlphaTauri", "AT02")
        Chasis.create_chasis("Williams", "FW43B")
        Chasis.create_chasis("Alfa Romeo", "C41")
        Chasis.create_chasis("Haas", "VF-21")
        Chasis.create_chasis("Mercedes", "W12")
        Chasis.create_chasis("Red Bull Racing", "RB16B")
        Chasis.create_chasis("Ferrari", "SF21")
        Chasis.create_chasis("McLaren", "MCL35M")
        Chasis.create_chasis("Aston Martin", "AMR21")
        Chasis.create_chasis("Alpine", "A521")
        Chasis.create_chasis("AlphaTauri", "AT02")
        Chasis.create_chasis("Williams", "FW43B")
        Chasis.create_chasis("Alfa Romeo", "C41")
        Chasis.create_chasis("Haas", "VF-21")
        Chasis.create_chasis("Mercedes", "W12")
        Chasis.create_chasis("Red Bull Racing", "RB16B")
        Chasis.create_chasis("Ferrari", "SF21")
        Chasis.create_chasis("McLaren", "MCL35M")
        Chasis.create_chasis("Aston Martin", "AMR21")
        Chasis.create_chasis("Alpine", "A521")
        Chasis.create_chasis("AlphaTauri", "AT02")
        Chasis.create_chasis("Williams", "FW43B")
        Chasis.create_chasis("Alfa Romeo", "C41")
        Chasis.create_chasis("Haas", "VF-21")
    
        #Piezas Mercedes
        Pieza.create_pieza("WingMaster 9000", "A", "Mercedes")
        Pieza.create_pieza("Aeroflare X1", "A", "Mercedes")
        Pieza.create_pieza("TurboWing Zephyr", "A", "Mercedes")
        Pieza.create_pieza("EcoWing Blade", "A", "Mercedes")
        Pieza.create_pieza("HyperWing Fury", "A", "Mercedes")
        Pieza.create_pieza("MegaFlow Glide", "A", "Mercedes")
        Pieza.create_pieza("AeroDynamics X", "A", "Mercedes")
        Pieza.create_pieza("TurboJetstream 500", "A", "Mercedes")
        Pieza.create_pieza("SkySlicer Aero", "A", "Mercedes")
        Pieza.create_pieza("AeroWing Infinity", "A", "Mercedes")
        
        Pieza.create_pieza("TurboThunder V8", "M", "Mercedes")
        Pieza.create_pieza("PowerBeast Pro", "M", "Mercedes")
        Pieza.create_pieza("NitroCharger Elite", "M", "Mercedes")
        Pieza.create_pieza("TurboBoost X12", "M", "Mercedes")
        Pieza.create_pieza("ThunderDrive 2000", "M", "Mercedes")
        Pieza.create_pieza("HyperVelocity Engine", "M", "Mercedes")
        Pieza.create_pieza("TurboJet 9000X", "M", "Mercedes")
        Pieza.create_pieza("PowerPulse Pro", "M", "Mercedes")
        Pieza.create_pieza("TurboDrive XL", "M", "Mercedes")
        Pieza.create_pieza("RocketForce 3000", "M", "Mercedes")
        
        Pieza.create_pieza("AeroGlide Thunder", "N", "Mercedes")
        Pieza.create_pieza("GripMaster Ultra", "N", "Mercedes")
        Pieza.create_pieza("TurboTread Exceed", "N", "Mercedes")
        Pieza.create_pieza("TrackThriller Max", "N", "Mercedes")
        Pieza.create_pieza("SpeedDive Storm", "N", "Mercedes")
        Pieza.create_pieza("AeroWheel X1", "N", "Mercedes")
        Pieza.create_pieza("SuperGrip Elite", "N", "Mercedes")
        Pieza.create_pieza("TurboGlide Pro", "N", "Mercedes")
        Pieza.create_pieza("MegaTraction Grip", "N", "Mercedes")
        Pieza.create_pieza("SpeedBlitz Thunder", "N", "Mercedes")
        
        #Piezas Red Bull Racing
        Pieza.create_pieza("AirMax Raptor", "A", "Red Bull Racing")
        Pieza.create_pieza("AirMax Raptor", "A", "Red Bull Racing")
        Pieza.create_pieza("AeroFlex Thunder", "A", "Red Bull Racing")
        Pieza.create_pieza("SkyWing Storm", "A", "Red Bull Racing")
        Pieza.create_pieza("TurboFlow Wingmaster", "A", "Red Bull Racing")
        Pieza.create_pieza("AeroJet Thrust", "A", "Red Bull Racing")
        Pieza.create_pieza("HyperGlide Speedster", "A", "Red Bull Racing")
        Pieza.create_pieza("AirSlicer BladeX", "A", "Red Bull Racing")
        Pieza.create_pieza("AeroFury Maxima", "A", "Red Bull Racing")
        Pieza.create_pieza("SkyForce AeroTech", "A", "Red Bull Racing")
        Pieza.create_pieza("TurboWing X7", "A", "Red Bull Racing")
        
        Pieza.create_pieza("NitroBeast X3", "M", "Red Bull Racing")
        Pieza.create_pieza("TurboCharger Storm", "M", "Red Bull Racing")
        Pieza.create_pieza("PowerGlide ProX", "M", "Red Bull Racing")
        Pieza.create_pieza("ThunderDrive X4", "M", "Red Bull Racing")
        Pieza.create_pieza("SpeedPulse Elite", "M", "Red Bull Racing")
        Pieza.create_pieza("TurboForce ThunderX", "M", "Red Bull Racing")
        Pieza.create_pieza("NitroJet Mach 7", "M", "Red Bull Racing")
        Pieza.create_pieza("PowerThriller X1", "M", "Red Bull Racing")
        Pieza.create_pieza("HyperBoost Maxima", "M", "Red Bull Racing")
        Pieza.create_pieza("TurboDrive Thunderstorm", "M", "Red Bull Racing")
        
        Pieza.create_pieza("GripMaster Thunderbolt", "N", "Red Bull Racing")
        Pieza.create_pieza("TurboGlide Blaze", "N", "Red Bull Racing")
        Pieza.create_pieza("AeroWheel Thunderstrike", "N", "Red Bull Racing")
        Pieza.create_pieza("SpeedBlitz StormRider", "N", "Red Bull Racing")
        Pieza.create_pieza("SkyGrip EliteX", "N", "Red Bull Racing")
        Pieza.create_pieza("TurboTread Thrustmaster", "N", "Red Bull Racing")
        Pieza.create_pieza("AeroGlide Thunderstrike", "N", "Red Bull Racing")
        Pieza.create_pieza("SpeedForce BlazeX", "N", "Red Bull Racing")
        Pieza.create_pieza("SkyBlitz StormRider", "N", "Red Bull Racing")
        Pieza.create_pieza("TurboSpeed EliteX", "N", "Red Bull Racing")
        
        #Piezas Ferrari
        Pieza.create_pieza("Scuderia AeroMaster", "A", "Ferrari")
        Pieza.create_pieza("TurboWing RedFire", "A", "Ferrari")
        Pieza.create_pieza("AeroFlow Thunderbolt", "A", "Ferrari")
        Pieza.create_pieza("Fireblade AeroX", "A", "Ferrari")
        Pieza.create_pieza("HyperAero Flame", "A", "Ferrari")
        Pieza.create_pieza("ThunderWing Inferno", "A", "Ferrari")
        Pieza.create_pieza("Firestorm AeroTech", "A", "Ferrari")
        Pieza.create_pieza("TurboFlare Maxima", "A", "Ferrari")
        Pieza.create_pieza("FireRider AeroBlitz", "A", "Ferrari")
        Pieza.create_pieza("AeroFury RedFusion", "A", "Ferrari")
        
        Pieza.create_pieza("FireBoost ThunderMax", "M", "Ferrari")
        Pieza.create_pieza("TurboFlame InfernoX", "M", "Ferrari")
        Pieza.create_pieza("AeroPower BlazeForce", "M", "Ferrari")
        Pieza.create_pieza("ThunderDrive FireStorm", "M", "Ferrari")
        Pieza.create_pieza("FirePulse FlameX", "M", "Ferrari")
        Pieza.create_pieza("HyperFlame InfernoStorm", "M", "Ferrari")
        Pieza.create_pieza("FireJet ThunderX", "M", "Ferrari")
        Pieza.create_pieza("TurboInferno BlazeRider", "M", "Ferrari")
        Pieza.create_pieza("FireTech ThunderBlitz", "M", "Ferrari")
        Pieza.create_pieza("TurboFusion BlazeMaster", "M", "Ferrari")
        
        Pieza.create_pieza("GripBlaze Thunderstrike", "N", "Ferrari")
        Pieza.create_pieza("TurboRider FireGlide", "N", "Ferrari")
        Pieza.create_pieza("AeroBlaze InfernoWheel", "N", "Ferrari")
        Pieza.create_pieza("SpeedInferno ThunderRider", "N", "Ferrari")
        Pieza.create_pieza("FireGlide BlazeX", "N", "Ferrari")
        Pieza.create_pieza("TurboThunder FlameSpeed", "N", "Ferrari")
        Pieza.create_pieza("AeroFlame InfernoStorm", "N", "Ferrari")
        Pieza.create_pieza("SpeedBlitz BlazeTech", "N", "Ferrari")
        Pieza.create_pieza("FireSpeed ThunderBlitz", "N", "Ferrari")
        Pieza.create_pieza("TurboStorm InfernoX", "N", "Ferrari")
        
        #Piezas McLaren
        Pieza.create_pieza("MegaFlow Airexcel", "A", "McLaren")
        Pieza.create_pieza("TurboJet Wingblaze", "A", "McLaren")
        Pieza.create_pieza("SkyRider AeroJet", "A", "McLaren")
        Pieza.create_pieza("AeroDynamics ProWing", "A", "McLaren")
        Pieza.create_pieza("HyperWing ThunderGlide", "A", "McLaren")
        Pieza.create_pieza("AeroMaster JetStorm", "A", "McLaren")
        Pieza.create_pieza("TurboFlare AeroFlow", "A", "McLaren")
        Pieza.create_pieza("AeroX ThunderBlitz", "A", "McLaren")
        Pieza.create_pieza("SkyForce AeroFury", "A", "McLaren")
        Pieza.create_pieza("TurboWing Infinity", "A", "McLaren")
        
        Pieza.create_pieza("TurboThunder EngineX", "M", "McLaren")
        Pieza.create_pieza("PowerBeast ThunderFire", "M", "McLaren")
        Pieza.create_pieza("NitroCharger StormBlade", "M", "McLaren")
        Pieza.create_pieza("TurboBoost FireX", "M", "McLaren")
        Pieza.create_pieza("ThunderDrive VelocityX", "M", "McLaren")
        Pieza.create_pieza("HyperVelocity TurboJet", "M", "McLaren")
        Pieza.create_pieza("TurboJet FlameThunder", "M", "McLaren")
        Pieza.create_pieza("PowerPulse ThunderForce", "M", "McLaren")
        Pieza.create_pieza("TurboDrive BlazeSpeed", "M", "McLaren")
        Pieza.create_pieza("RocketForce VelocityStorm", "M", "McLaren")
        
        Pieza.create_pieza("AeroGlide BlazeSpeed", "N", "McLaren")
        Pieza.create_pieza("GripMaster ThunderJet", "N", "McLaren")
        Pieza.create_pieza("TurboTread VelocityTech", "N", "McLaren")
        Pieza.create_pieza("TrackThriller ThunderX", "N", "McLaren")
        Pieza.create_pieza("SpeedDive BlazeGlide", "N", "McLaren")
        Pieza.create_pieza("AeroWheel ThunderRider", "N", "McLaren")
        Pieza.create_pieza("SuperGrip VelocityMax", "N", "McLaren")
        Pieza.create_pieza("TurboGlide BlazeStorm", "N", "McLaren")
        Pieza.create_pieza("MegaTraction ThunderBlitz", "N", "McLaren")
        Pieza.create_pieza("SpeedBlitz BlazeTech", "N", "McLaren")
        
        #Piezas Aston Martin
        Pieza.create_pieza("AeroMaster VantageX", "A", "Aston Martin")
        Pieza.create_pieza("TurboWing RapidStorm", "A", "Aston Martin")
        Pieza.create_pieza("SkyRider AeroVantage", "A", "Aston Martin")
        Pieza.create_pieza("AeroDynamics StormVantage", "A", "Aston Martin")
        Pieza.create_pieza("HyperWing ThunderVantage", "A", "Aston Martin")
        Pieza.create_pieza("AeroJet StormMaster", "A", "Aston Martin")
        Pieza.create_pieza("TurboFlare AeroBolt", "A", "Aston Martin")
        Pieza.create_pieza("AeroX ThunderWave", "A", "Aston Martin")
        Pieza.create_pieza("SkyForce AeroVortex", "A", "Aston Martin")
        Pieza.create_pieza("TurboWing VantageBlitz", "A", "Aston Martin")
        
        Pieza.create_pieza("TurboThunder VantagePro", "M", "Aston Martin")
        Pieza.create_pieza("PowerBeast RapidFire", "M", "Aston Martin")
        Pieza.create_pieza("NitroCharger StormBolt", "M", "Aston Martin")
        Pieza.create_pieza("TurboBoost VantageX", "M", "Aston Martin")
        Pieza.create_pieza("ThunderDrive Thunderbolt", "M", "Aston Martin")
        Pieza.create_pieza("HyperVelocity TurboWave", "M", "Aston Martin")
        Pieza.create_pieza("TurboJet StormVortex", "M", "Aston Martin")
        Pieza.create_pieza("PowerPulse ThunderBolt", "M", "Aston Martin")
        Pieza.create_pieza("TurboDrive VantageMax", "M", "Aston Martin")
        Pieza.create_pieza("RocketForce StormBlitz", "M", "Aston Martin")
        
        Pieza.create_pieza("AeroGlide RapidSpeed", "N", "Aston Martin")
        Pieza.create_pieza("GripMaster ThunderVortex", "N", "Aston Martin")
        Pieza.create_pieza("TurboTread VantageTech", "N", "Aston Martin")
        Pieza.create_pieza("TrackThriller ThunderBlitz", "N", "Aston Martin")
        Pieza.create_pieza("SpeedDive RapidGlide", "N", "Aston Martin")
        Pieza.create_pieza("AeroWheel ThunderMaster", "N", "Aston Martin")
        Pieza.create_pieza("SuperGrip VantageMaxima", "N", "Aston Martin")
        Pieza.create_pieza("TurboGlide StormRider", "N", "Aston Martin")
        Pieza.create_pieza("MegaTraction ThunderTech", "N", "Aston Martin")
        Pieza.create_pieza("SpeedBlitz VantageTechX", "N", "Aston Martin")
        
        #Piezas Alpine
        Pieza.create_pieza("AeroMaster AlpineX", "A", "Alpine")
        Pieza.create_pieza("TurboWing GlacierStorm", "A", "Alpine")
        Pieza.create_pieza("SkyRider AeroFrost", "A", "Alpine")
        Pieza.create_pieza("AeroDynamics IceGlide", "A", "Alpine")
        Pieza.create_pieza("HyperWing FrostBolt", "A", "Alpine")
        Pieza.create_pieza("AeroJet SnowRider", "A", "Alpine")
        Pieza.create_pieza("TurboFlare IcyWave", "A", "Alpine")
        Pieza.create_pieza("AeroX AlpineBlitz", "A", "Alpine")
        Pieza.create_pieza("SkyForce FrostVortex", "A", "Alpine")
        Pieza.create_pieza("TurboWing GlacierBlade", "A", "Alpine")
        
        Pieza.create_pieza("TurboThunder FrostMaster", "M", "Alpine")
        Pieza.create_pieza("PowerBeast IceStorm", "M", "Alpine")
        Pieza.create_pieza("NitroCharger SnowBolt", "M", "Alpine")
        Pieza.create_pieza("TurboBoost AlpineX", "M", "Alpine")
        Pieza.create_pieza("ThunderDrive Frostbolt", "M", "Alpine")
        Pieza.create_pieza("HyperVelocity SnowJet", "M", "Alpine")
        Pieza.create_pieza("TurboJet IceVortex", "M", "Alpine")
        Pieza.create_pieza("PowerPulse FrostBlitz", "M", "Alpine")
        Pieza.create_pieza("TurboDrive AlpineTech", "M", "Alpine")
        Pieza.create_pieza("RocketForce SnowRider", "M", "Alpine")
        
        Pieza.create_pieza("AeroGlide FrostSpeed", "N", "Alpine")
        Pieza.create_pieza("GripMaster SnowVortex", "N", "Alpine")
        Pieza.create_pieza("TurboTread AlpineTech", "N", "Alpine")
        Pieza.create_pieza("TrackThriller SnowBlitz", "N", "Alpine")
        Pieza.create_pieza("SpeedDive FrostGlide", "N", "Alpine")
        Pieza.create_pieza("AeroWheel IceMaster", "N", "Alpine")
        Pieza.create_pieza("SuperGrip AlpineMaxima", "N", "Alpine")
        Pieza.create_pieza("TurboGlide SnowTech", "N", "Alpine")
        Pieza.create_pieza("MegaTraction FrostBlade", "N", "Alpine")
        Pieza.create_pieza("SpeedBlitz AlpineStorm", "N", "Alpine")
        
        #Piezas AlphaTauri
        Pieza.create_pieza("AeroMaster AlphaFlow", "A", "AlphaTauri")
        Pieza.create_pieza("TurboWing TauriStorm", "A", "AlphaTauri")
        Pieza.create_pieza("SkyRider AeroBolt", "A", "AlphaTauri")
        Pieza.create_pieza("AeroDynamics StormFlow", "A", "AlphaTauri")
        Pieza.create_pieza("HyperWing TauriBlade", "A", "AlphaTauri")
        Pieza.create_pieza("AeroJet BoltMaster", "A", "AlphaTauri")
        Pieza.create_pieza("TurboFlare AlphaX", "A", "AlphaTauri")
        Pieza.create_pieza("AeroX TauriBlitz", "A", "AlphaTauri")
        Pieza.create_pieza("SkyForce AeroFury", "A", "AlphaTauri")
        Pieza.create_pieza("TurboWing StormWave", "A", "AlphaTauri")
        
        Pieza.create_pieza("TurboThunder TauriMaster", "M", "AlphaTauri")
        Pieza.create_pieza("PowerBeast StormJet", "M", "AlphaTauri")
        Pieza.create_pieza("NitroCharger AlphaBolt", "M", "AlphaTauri")
        Pieza.create_pieza("TurboBoost TauriBlitz", "M", "AlphaTauri")
        Pieza.create_pieza("ThunderDrive StormFlow", "M", "AlphaTauri")
        Pieza.create_pieza("HyperVelocity AlphaJet", "M", "AlphaTauri")
        Pieza.create_pieza("TurboJet BoltX", "M", "AlphaTauri")
        Pieza.create_pieza("PowerPulse TauriTech", "M", "AlphaTauri")
        Pieza.create_pieza("TurboDrive StormBlitz", "M", "AlphaTauri")
        Pieza.create_pieza("RocketForce AlphaRider", "M", "AlphaTauri")
        
        Pieza.create_pieza("AeroGlide TauriSpeed", "N", "AlphaTauri")
        Pieza.create_pieza("GripMaster StormVortex", "N", "AlphaTauri")
        Pieza.create_pieza("TurboTread AlphaTech", "N", "AlphaTauri")
        Pieza.create_pieza("TrackThriller TauriBlitz", "N", "AlphaTauri")
        Pieza.create_pieza("SpeedDive StormGlide", "N", "AlphaTauri")
        Pieza.create_pieza("AeroWheel BoltMaster", "N", "AlphaTauri")
        Pieza.create_pieza("SuperGrip TauriMaxima", "N", "AlphaTauri")
        Pieza.create_pieza("TurboGlide StormTech", "N", "AlphaTauri")
        Pieza.create_pieza("MegaTraction AlphaBlade", "N", "AlphaTauri")
        Pieza.create_pieza("SpeedBlitz TauriStormX", "N", "AlphaTauri")
        
        #Piezas Williams
        Pieza.create_pieza("AeroMaster SpeedWing", "A", "Williams")
        Pieza.create_pieza("TurboWing VelocityStorm", "A", "Williams")
        Pieza.create_pieza("SkyRider AeroBolt", "A", "Williams")
        Pieza.create_pieza("AeroDynamics StormFlow", "A", "Williams")
        Pieza.create_pieza("HyperWing ThunderBolt", "A", "Williams")
        Pieza.create_pieza("AeroJet BoltMaster", "A", "Williams")
        Pieza.create_pieza("TurboFlare SpeedX", "A", "Williams")
        Pieza.create_pieza("AeroX WilliamsBlitz", "A", "Williams")
        Pieza.create_pieza("SkyForce AeroFury", "A", "Williams")
        Pieza.create_pieza("TurboWing VelocityWave", "A", "Williams")
        
        Pieza.create_pieza("TurboThunder WilliamsMaster", "M", "Williams")
        Pieza.create_pieza("PowerBeast VelocityJet", "M", "Williams")
        Pieza.create_pieza("NitroCharger AeroBolt", "M", "Williams")
        Pieza.create_pieza("TurboBoost WilliamsBlitz", "M", "Williams")
        Pieza.create_pieza("ThunderDrive VelocityFlow", "M", "Williams")
        Pieza.create_pieza("HyperVelocity AeroJet", "M", "Williams")
        Pieza.create_pieza("TurboJet BoltX", "M", "Williams")
        Pieza.create_pieza("PowerPulse WilliamsTech", "M", "Williams")
        Pieza.create_pieza("TurboDrive VelocityBlitz", "M", "Williams")
        Pieza.create_pieza("RocketForce AeroRider", "M", "Williams")
        
        Pieza.create_pieza("AeroGlide WilliamsSpeed", "N", "Williams")
        Pieza.create_pieza("GripMaster VelocityVortex", "N", "Williams")
        Pieza.create_pieza("TurboTread AeroTech", "N", "Williams")
        Pieza.create_pieza("TrackThriller WilliamsBlitz", "N", "Williams")
        Pieza.create_pieza("SpeedDive VelocityGlide", "N", "Williams")
        Pieza.create_pieza("AeroWheel BoltMaster", "N", "Williams")
        Pieza.create_pieza("SuperGrip WilliamsMaxima", "N", "Williams")
        Pieza.create_pieza("TurboGlide VelocityTech", "N", "Williams")
        Pieza.create_pieza("MegaTraction AeroBlade", "N", "Williams")
        Pieza.create_pieza("SpeedBlitz WilliamsStorm", "N", "Williams")
        
        #Piezas Alfa Romeo
        Pieza.create_pieza("AeroMaster AlfaFlow", "A", "Alfa Romeo")
        Pieza.create_pieza("TurboWing RomeoStorm", "A", "Alfa Romeo")
        Pieza.create_pieza("SkyRider AeroBolt", "A", "Alfa Romeo")
        Pieza.create_pieza("AeroDynamics StormFlow", "A", "Alfa Romeo")
        Pieza.create_pieza("HyperWing ThunderBolt", "A", "Alfa Romeo")
        Pieza.create_pieza("AeroJet BoltMaster", "A", "Alfa Romeo")
        Pieza.create_pieza("TurboFlare AlfaX", "A", "Alfa Romeo")
        Pieza.create_pieza("AeroX RomeoBlitz", "A", "Alfa Romeo")
        Pieza.create_pieza("SkyForce AeroFury", "A", "Alfa Romeo")
        Pieza.create_pieza("TurboWing RomeoWave", "A", "Alfa Romeo")
        
        Pieza.create_pieza("TurboThunder RomeoMaster", "M", "Alfa Romeo")
        Pieza.create_pieza("PowerBeast RomeoJet", "M", "Alfa Romeo")
        Pieza.create_pieza("NitroCharger AeroBolt", "M", "Alfa Romeo")
        Pieza.create_pieza("TurboBoost RomeoBlitz", "M", "Alfa Romeo")
        Pieza.create_pieza("ThunderDrive StormFlow", "M", "Alfa Romeo")
        Pieza.create_pieza("HyperVelocity AlfaJet", "M", "Alfa Romeo")
        Pieza.create_pieza("TurboJet BoltX", "M", "Alfa Romeo")
        Pieza.create_pieza("PowerPulse RomeoTech", "M", "Alfa Romeo")
        Pieza.create_pieza("TurboDrive StormBlitz", "M", "Alfa Romeo")
        Pieza.create_pieza("RocketForce AlfaRider", "M", "Alfa Romeo")
        
        Pieza.create_pieza("AeroGlide RomeoSpeed", "N", "Alfa Romeo")
        Pieza.create_pieza("GripMaster StormVortex", "N", "Alfa Romeo")
        Pieza.create_pieza("TurboTread AlfaTech", "N", "Alfa Romeo")
        Pieza.create_pieza("TrackThriller RomeoBlitz", "N", "Alfa Romeo")
        Pieza.create_pieza("SpeedDive StormGlide", "N", "Alfa Romeo")
        Pieza.create_pieza("AeroWheel BoltMaster", "N", "Alfa Romeo")
        Pieza.create_pieza("SuperGrip RomeoMaxima", "N", "Alfa Romeo")
        Pieza.create_pieza("TurboGlide StormTech", "N", "Alfa Romeo")
        Pieza.create_pieza("MegaTraction AlfaBlade", "N", "Alfa Romeo")
        Pieza.create_pieza("SpeedBlitz RomeoStormX", "N", "Alfa Romeo")
        
        #Piezas Haas
        
        Pieza.create_pieza("AeroMaster HaasFlow", "A", "Haas")
        Pieza.create_pieza("TurboWing VelocityStorm", "A", "Haas")
        Pieza.create_pieza("SkyRider AeroBolt", "A", "Haas")
        Pieza.create_pieza("AeroDynamics StormFlow", "A", "Haas")
        Pieza.create_pieza("HyperWing ThunderBolt", "A", "Haas")
        Pieza.create_pieza("AeroJet BoltMaster", "A", "Haas")
        Pieza.create_pieza("TurboFlare HaasX", "A", "Haas")
        Pieza.create_pieza("AeroX HaasBlitz", "A", "Haas")
        Pieza.create_pieza("SkyForce AeroFury", "A", "Haas")
        Pieza.create_pieza("TurboWing VelocityWave", "A", "Haas")
        
        Pieza.create_pieza("TurboThunder HaasMaster", "M", "Haas")
        Pieza.create_pieza("PowerBeast VelocityJet", "M", "Haas")
        Pieza.create_pieza("NitroCharger AeroBolt", "M", "Haas")
        Pieza.create_pieza("TurboBoost HaasBlitz", "M", "Haas")
        Pieza.create_pieza("ThunderDrive StormFlow", "M", "Haas")
        Pieza.create_pieza("HyperVelocity HaasJet", "M", "Haas")
        Pieza.create_pieza("TurboJet BoltX", "M", "Haas")
        Pieza.create_pieza("PowerPulse HaasTech", "M", "Haas")
        Pieza.create_pieza("TurboDrive StormBlitz", "M", "Haas")
        Pieza.create_pieza("RocketForce HaasRider", "M", "Haas")
        
        Pieza.create_pieza("AeroGlide HaasSpeed", "N", "Haas")
        Pieza.create_pieza("GripMaster StormVortex", "N", "Haas")
        Pieza.create_pieza("TurboTread HaasTech", "N", "Haas")
        Pieza.create_pieza("TrackThriller HaasBlitz", "N", "Haas")
        Pieza.create_pieza("SpeedDive StormGlide", "N", "Haas")
        Pieza.create_pieza("AeroWheel BoltMaster", "N", "Haas")
        Pieza.create_pieza("SuperGrip HaasMaxima", "N", "Haas")
        Pieza.create_pieza("TurboGlide StormTech", "N", "Haas")
        Pieza.create_pieza("MegaTraction HaasBlade", "N", "Haas")
        Pieza.create_pieza("SpeedBlitz HaasStormX", "N", "Haas")

        
        # Asignando las cosas 
        Piloto.asignar_equipo()
        